site_name: CMSIS MLEK Machine Learning Evaluation Kit (MLEK)
repo_url: https://github.com/ARM-Examples/cmsis-mlek
edit_uri: ./edit/main/documentation
nav:
    - Home: index.md
    - Overview: overview.md
    - Audio Template Applications: templates_audio.md
    - Video Template Applications: templates_video.md
    - Target Configuration Hardware Boards: target_configuration_refapp.md
    -  Target Configuration Arm Virtual Hardware: target_configuration_avh.md

plugins:
    - search
   # - mermaid2    # pip install mkdocs-mermaid2-plugin

theme:
  name: readthedocs
markdown_extensions:
  - admonition
extra_css:
  - css/extra.css
docs_dir: documentation
site_dir: docs
use_directory_urls: false
