site_name: CMSIS MLEK Machine Learning Evaluation Kit (MLEK)
repo_url: https://github.com/ARM-software/cmsis-mlek
edit_uri: ./edit/main/documentation
nav:
    - Home: index.md
    - Overview: overview.md
    - Template Applications: template.md

plugins:
    - search
   # - mermaid2    # pip install mkdocs-mermaid2-plugin

theme:
  name: readthedocs
markdown_extensions:
  - admonition
extra_css:
  - css/extra.css
docs_dir: documentation
site_dir: docs
use_directory_urls: false
